name: music_player
description: A new Flutter project.

version: 0.5.4+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  http: ^0.13.0
  logger: ^1.1.0
  google_fonts: ^2.1.0
  carousel_slider: ^4.0.0
  dio: ^4.0.1

  redux: ^5.0.0
  rxdart: ^0.26.0
  redux_epics: ^0.15.0
  flutter_redux: ^0.8.2
  flutter_redux_navigation: ^0.7.0
  auto_route: 2.4.0
  auto_route_generator: 2.4.0

    # FireBase
  firebase_core: 1.2.0
  firebase_messaging: 10.0.0
  firebase_auth: 1.2.0

  connectivity: ^3.0.1

  cached_network_image: 3.1.0+1
  url_launcher: ^6.0.0
  flutter_svg: ^0.23.0+1
  share: ^2.0.4
  assets_audio_player: ^3.0.3


  visibility_detector: ^0.2.2
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^2.3.0
  build_resolvers: ^2.0.4
  json_serializable: ^4.1.1
  build_runner: ^2.1.1
  freezed: ^0.14.0
  freezed_annotation: ^0.14.0

flutter_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/gif/
    - assets/jpg/